#!/usr/bin/env ruby
# frozen_string_literal: true

require "optparse"

$LOAD_PATH.unshift File.expand_path("../lib", __dir__)
require "igitsh"

OptionParser.new do |parser|
  parser.banner = <<-BANNER
  igitsh -- an interactive shell for git

  This shell includes completions and history.
  Run any `git` command without prefixing `git`.

  Options:
  BANNER

  parser.on("--history-file", "Path to the history file") do
    puts Igitsh::HISTORY_FILE_PATH
    exit
  end

  parser.on("-v", "--version", "Show the current version") do
    puts Igitsh::VERSION
    exit
  end

  parser.on("-h", "--help", "Show this help page") do
    puts parser
    exit
  end
end.parse!

Igitsh.run!
